Dev
Maksysko/C-training pull request #2
Opened 2019-07-10 09:49 UTC by Maksysko

short way app

2019-07-11 04:57 UTC, reczepio commented on graph/Graph/Graph.cpp
> +Graph::Graph(int& size_t, std::vector<std::vector<int>>& graph) : size(size_t) {
I would rather suggest create new type.

2019-07-11 06:35 UTC, mjtieto commented on exercise_0/CMakeLists.txt
> +include_directories(terminalMode)
In modern CMake, `target_include_directories` is preferred. It allows you to set different include paths for different targets (executables, libraries etc). When you use `include_directories`, the whole project is affected.

2019-07-11 06:40 UTC, mjtieto commented on exercise_0/characterCounter/CharacterCounter.h
> +    void printCounts() const;
Implementing prints and formatting is usually done by implementing `operator <<`. Check out this example: https://coliru.stacked-crooked.com/view?id=17454ddf4005320d

2019-07-11 06:40 UTC, mjtieto commented on exercise_0/fileMode/FileMode.cpp
> +int FileMode::run(const std::string &path) {
Method could return a `bool`.

2019-07-11 06:42 UTC, mjtieto commented on exercise_0/fileMode/FileMode.h
> +#include "../characterCounter/CharacterCounter.h"
Like I said previously, please avoid relative includes. Check out this comment: https://github.com/Maksysko/C-training/pull/1#discussion_r300368297

2019-07-11 06:45 UTC, reczepio commented on graph/Graph/Graph.cpp
> +    way = new std::string[size];
We'd rather use just std::string, no pointer to it. 
std::string allocates memory automatically (when needed)

2019-07-11 06:47 UTC, mjtieto commented on graph/Graph/Graph.h
> +    int* distance;
`matrix`, `visited` and `distance` should be `std::vector`s:
`std::vector<bool> visited`
`std::vector<int> distance`
`std::vector<std::vector<int>> matrix`

2019-07-11 06:47 UTC, reczepio commented on graph/Graph/Graph.cpp
> +    matrix = new int*[size];
Please init on initialization list.

2019-07-11 06:48 UTC, reczepio commented on graph/Graph/Graph.cpp
> +        matrix[graph[i][0]][graph[i][1]] = graph[i][2];
Hardly readable.

2019-07-11 06:53 UTC, reczepio commented on graph/Graph/Graph.cpp
> +    visited = new bool[size];
Rather do not use raw arrays. Preferred are standard containers like:
map, vector, std::array (this is something different then raw array), list, end so on...

2019-07-11 06:53 UTC, reczepio commented on graph/Graph/Graph.cpp
> +    for (int i = 0; i < size; i++){
pre incrementation

2019-07-11 06:54 UTC, reczepio commented on graph/Graph/Graph.h
> +    const int infinity = std::numeric_limits<int>::max();
Missleading name - this is not infinity but max int value.

2019-07-11 06:56 UTC, reczepio commented on graph/Graph/Graph.cpp
> +     way[startVertex] = std::to_string(startVertex);
I think, better is to store way as a std::vector<int>.

2019-07-11 06:56 UTC, reczepio commented on graph/Graph/Graph.cpp
> +     for (int vertex = 0; vertex < size - 1; vertex++){
pre incrementation

2019-07-11 06:57 UTC, reczepio commented on graph/Graph/Graph.cpp
> +         for (int i = 0; i < size; i++){
Pre incrementation

2019-07-11 06:58 UTC, reczepio commented on graph/Graph/Graph.cpp
> +             if (!visited[i] && matrix[currentVertex][i] && distance[currentVertex]!= infinity &&
Too long condition. I do not have any idea, what you intend to check. better is to create function like:
bool is_some_condition_fullfiled() 
and put the condition inside

2019-07-11 07:00 UTC, reczepio commented on graph/Graph/Graph.h
> +public:
(This is not mistake).
In C++ we rather put "public" before "private". Order is:
public
protected
private

2019-07-11 07:02 UTC, reczepio commented on graph/main.cpp
> +        node = {x, y, weight};
Maybe worth to create separate class Node?

2019-07-11 07:03 UTC, reczepio commented on graph/main.cpp
> +        vertex.push_back(x);
I would rather suggest to create own "class Vertex".

2019-07-11 07:05 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> +Graph::Graph(int& size_t, std::vector<std::vector<int>>& graph) : size(size_t) {
The "_t" suffix is a convention for data type. Please don't use it with parameter names.

As a suggestion - if the typename gets really long you can use type alias with "typedef" or "using"
i.e. "using Matrix = std::vector<std::vector<int>>". 
Then Matrix can be used whenever you need a type in a given scope.

2019-07-11 07:05 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> +    way = new std::string[size];
It would be safer using std::vector and reserving size instead of using dynamically allocated arrays.

2019-07-11 07:05 UTC, rmnkrc commented on graph/Graph/Graph.h
> +    void print();
If a method does not change the internal state of the object, mark is as const.
Also if a variable is not meant to be changed, mark is as const.
That helps other devs to understand your intentions and in some cases helps compiler to optimize the code.
This guideline relates to a topic of 'const correctness' in general.

2019-07-17 09:23 UTC, rmnkrc commented on graph/CMakeLists.txt
> +add_executable(graph main.cpp Graph/Graph.cpp Graph/Graph.h Vertices/Vertices.cpp Vertices/Vertices.h)
you actually don't need to include .h files here. Header files will be automatically included from .cpp files. One exception would be header only templates.

2019-07-17 09:23 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> +    for (int i = 0; i < vertices.getSize(); ++i)
minor: There is a special type for size related operations 'size_t'. It is unsigned, since size cannot be negative. When writing your own structures you may want to use it.

2019-07-17 09:23 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> +        int pathWeight = vertices.getVertexData(i, 2);
why don't you use const values instead of 0,1,2? Thing is 0,1,2 tells nothing about the data you extract and it may get messy if you add more data.

2019-07-17 09:23 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> +{
I would suggest introducing a new class ShortestWay that would be responsible for the algorithm.
That would separate holding/basic operations on Graph from the real algorithm.

Also 'go' as a name on 'Graph' class seems really confusing.

2019-07-17 09:23 UTC, rmnkrc commented on graph/Graph/Graph.cpp
>          getShortestWay();
get suggest that the method will return something. 'Compute' would be probably better in this context

2019-07-17 09:23 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> -    distance = new int[size];
I would suggest using std:: containers i.e. std::vector

2019-07-17 09:23 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> +void Graph::getShortestWay()
Please try separate computation from printing

2019-07-17 09:23 UTC, rmnkrc commented on graph/Graph/Graph.cpp
> +void Graph::createWay(const int currentVertex, const int vertex)
const int currentVertex - one notable exception:
the compiler ignores const in front of simple types when it creates the function/method signature.
This means that 
createWay(const int currentVertex, const int vertex) and createWay(int currentVertex, int vertex)
form the same signature and you will be given error if you try to create them both.
That is why devs usually do not write const in front of simple types.

2019-07-17 09:23 UTC, rmnkrc commented on graph/Vertices/Vertices.cpp
> +    vertices.push_back({startVertex, endVertex, weight});
you could use emplace_back in this context

2019-07-17 09:23 UTC, rmnkrc commented on graph/Vertices/Vertices.h
> +    int getUniqueVerticesCount() const;
good use of 'const' for methods! :)

2019-07-17 10:10 UTC, Maksysko commented on graph/Graph/Graph.cpp
> -    distance = new int[size];
It is old code. I am using vectors now

2019-07-17 10:44 UTC, Maksysko commented on graph/Vertices/Vertices.h
> +    int getUniqueVerticesCount() const;
https://github.com/Maksysko/C-training/pull/2#discussion_r304298392
There is no need to put const  for variables in addVertex function also according this comment. Am I right?

2019-07-17 11:15 UTC, rmnkrc commented on graph/Vertices/Vertices.h
> +    int getUniqueVerticesCount() const;
nope, no reason

2019-07-17 11:34 UTC, Maksysko commented on graph/Vertices/Vertices.h
> +    int getUniqueVerticesCount() const;
Thx

2019-07-17 15:47 UTC, rmnkrc commented on graph/ShortestWay/ShortestWay.h
> +private:
it is easier to read if you separate private methods from private variables. You may add the 'private:' keyword twice

2019-07-17 15:47 UTC, rmnkrc commented on graph/ShortestWay/ShortestWay.h
> +    const int startNodeIndex;
constant variables that are not related to the particular class instance are better of defined as constexpr or static consts before the class definition.

2019-07-17 15:47 UTC, rmnkrc commented on graph/ShortestWay/ShortestWay.h
> +    ~ShortestWay ();
= default

2019-07-17 15:47 UTC, rmnkrc commented on graph/ShortestWay/ShortestWay.h
> +using boolVector = std::vector<bool>;
fun fact:  std::vector<bool> has special implementation, different then the default std::vector.

2019-07-18 15:07 UTC, rmnkrc requested changes
Ok, one more change and I think we can finish this assignment

2019-07-18 15:07 UTC, rmnkrc commented on graph/ShortestWay/ShortestWay.cpp
> +visited(size, false),
If you only use the variable for one method, it can be local

2019-07-18 15:07 UTC, rmnkrc commented on graph/ShortestWay/ShortestWay.cpp
> +{
we can accept this solution. if we wanted to improve on it then we would separate print from the algorithm. That way you could have many different printing targets i.e. file, cout, database .... now you are tied to the cout.

2019-07-19 12:42 UTC, rmnkrc approved these changes
alright, it is much better now :) took us a bit of time, thought. Please start the next task

2019-07-25 13:26 UTC, merged